# Homework Week 1

## Numpy & Pandas HW

#### 1. 주어진 DataFrame 컬럼 순서 바꾸기 (서로 다른 종류 3가지 이상)
- iloc, loc, append, concat 함수 또는 컬럼 인덱싱으로 DataFrame의 컬럼 순서를 바꿔보세요. Numpy 행렬로 변환했다가 DataFrame으로 만드셔도 됩니다.

In [1]:
from os.path import join

import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(np.random.uniform(0, 1, size=(10, 3)), columns=['A', 'B', 'C'])
df

A         B         C
0  0.170395  0.293128  0.301162
1  0.379944  0.498647  0.021255
2  0.183947  0.721333  0.872580
3  0.482715  0.316301  0.841127
4  0.431866  0.922759  0.275604
5  0.352787  0.960322  0.039054
6  0.235591  0.018865  0.093037
7  0.562341  0.284166  0.758842
8  0.550060  0.837803  0.349137
9  0.037572  0.673437  0.792959

In [3]:
# 1
cols = df.columns[[1,2,0]]
df[cols]

B         C         A
0  0.293128  0.301162  0.170395
1  0.498647  0.021255  0.379944
2  0.721333  0.872580  0.183947
3  0.316301  0.841127  0.482715
4  0.922759  0.275604  0.431866
5  0.960322  0.039054  0.352787
6  0.018865  0.093037  0.235591
7  0.284166  0.758842  0.562341
8  0.837803  0.349137  0.550060
9  0.673437  0.792959  0.037572

In [4]:
# 2
df.loc[:,['B','C','A']]

B         C         A
0  0.293128  0.301162  0.170395
1  0.498647  0.021255  0.379944
2  0.721333  0.872580  0.183947
3  0.316301  0.841127  0.482715
4  0.922759  0.275604  0.431866
5  0.960322  0.039054  0.352787
6  0.018865  0.093037  0.235591
7  0.284166  0.758842  0.562341
8  0.837803  0.349137  0.550060
9  0.673437  0.792959  0.037572

In [5]:
# 3
df.iloc[:,[1,2,0]]

B         C         A
0  0.293128  0.301162  0.170395
1  0.498647  0.021255  0.379944
2  0.721333  0.872580  0.183947
3  0.316301  0.841127  0.482715
4  0.922759  0.275604  0.431866
5  0.960322  0.039054  0.352787
6  0.018865  0.093037  0.235591
7  0.284166  0.758842  0.562341
8  0.837803  0.349137  0.550060
9  0.673437  0.792959  0.037572

#### 2. 주어진 행렬의 각 원소 값을 해당 열의 평균 값으로 빼기
- Numpy.mean() 함수와 브로드캐스팅 기능 사용

In [8]:
A = np.array(np.random.randint(0, 5, size=(5, 6)))
A

array([[3, 0, 4, 1, 4, 1],
       [3, 1, 2, 4, 0, 1],
       [0, 4, 4, 3, 2, 0],
       [3, 2, 1, 4, 4, 4],
       [2, 1, 3, 0, 2, 2]])

In [18]:
mean = np.mean(A, axis = 1)
mean = mean.reshape(5,1)
mean

array([[2.16666667],
       [1.83333333],
       [2.16666667],
       [3.        ],
       [1.66666667]])

In [19]:
A - mean

array([[ 0.83333333, -2.16666667,  1.83333333, -1.16666667,  1.83333333,
        -1.16666667],
       [ 1.16666667, -0.83333333,  0.16666667,  2.16666667, -1.83333333,
        -0.83333333],
       [-2.16666667,  1.83333333,  1.83333333,  0.83333333, -0.16666667,
        -2.16666667],
       [ 0.        , -1.        , -2.        ,  1.        ,  1.        ,
         1.        ],
       [ 0.33333333, -0.66666667,  1.33333333, -1.66666667,  0.33333333,
         0.33333333]])